server:
  port: ${SERVER_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI}

  data:
    mongodb:
      host: ${DATA_MONGODB_HOST}
      port: ${DATA_MONGODB_PORT}
      database: ${DATA_MONGODB_DATABASE}